#!/bin/bash
# assets/faces/*.png を base64 の data URI にして src/faces.js を生成する
cd "$(dirname "$0")/.."
out=src/faces.js
echo "// generated by scripts/build-faces.sh — do not edit" > $out
echo "const FACE_DATA = {" >> $out
for f in assets/faces/*.png; do
  name=$(basename "$f" .png)
  b64=$(base64 -i "$f" | tr -d '\n')
  echo "  ${name}: \"data:image/png;base64,${b64}\"," >> $out
done
echo "};" >> $out
echo "generated $out ($(wc -c < $out | tr -d ' ') bytes)"
