#!/bin/bash
# 御霊の顔アイコン src/faces.js を、公式配布の顔アイコン(透過)から生成する。
# 出どころ: kitan-lore MCP get_spirit の sheets「顔アイコン(透過)」(1024x1024 webp)
#   https://vibe.co.jp/luna-occulta/media/img/canon/<id>_icon.webp
#
# 玉は段位ごとに大きさが違う（src/game.js の TIERS の r = 18〜90）。canvas の裏地は
# 盤面 480px 固定 × dpr 上限 2 なので、玉が実際に使う画素は最大でも r*4。段位ごとに
# その実寸へ縮めてから data URI 化する（一律サイズだと小玉が無駄に重く、大玉は足りない。
# Artifact 版は 16MB の上限が近いので、ここの重さがそのまま効く）。
#
# 縮小した PNG は assets/faces/ にも残す（scripts/ogp-card.html がここを読む）。
set -euo pipefail
cd "$(dirname "$0")/.."
TMP=.tmp_faces
mkdir -p "$TMP" assets/faces
trap 'rm -rf "$TMP"' EXIT

# <id>:<px>   px は TIERS の r*4 を 32 の倍数へ切り上げた値
SIZES=(nemu:96 oto:96 anne:128 nekomata:160 benten:192 uka:256 izuna:288 shion:352 sakuya:384)

OUT=src/faces.js
{
  echo "// generated by scripts/build-faces.sh — do not edit"
  echo "// 公式配布の顔アイコン(透過)を段位ごとの実寸に縮小したもの"
  echo "// https://vibe.co.jp/luna-occulta/media/img/canon/<id>_icon.webp"
  echo "const FACE_DATA = {"
  for s in "${SIZES[@]}"; do
    id=${s%:*}
    px=${s#*:}
    curl -sf "https://vibe.co.jp/luna-occulta/media/img/canon/${id}_icon.webp" -o "$TMP/$id.webp"
    ffmpeg -y -loglevel error -sws_flags lanczos+accurate_rnd \
      -i "$TMP/$id.webp" -vf scale=$px:$px -pix_fmt rgba "assets/faces/$id.png"
    echo "  $id: \"data:image/png;base64,$(base64 -i "assets/faces/$id.png" | tr -d '\n')\","
  done
  echo "};"
} > "$OUT"
echo "$OUT: $(stat -f%z "$OUT") bytes (${#SIZES[@]} icons)"
