#!/bin/bash
# assets/audio/kitan_maintheme.m4a（公式メインテーマをAAC 80kbpsに再圧縮したもの）を
# data URI 化して src/bgm.js を生成する
cd "$(dirname "$0")/.."
out=src/bgm.js
echo "// generated by scripts/build-bgm.sh — do not edit" > $out
printf 'const BGM_DATA = "data:audio/mp4;base64,' >> $out
base64 -i assets/audio/kitan_maintheme.m4a | tr -d '\n' >> $out
printf '";\n' >> $out
echo "generated $out ($(wc -c < $out | tr -d ' ') bytes)"
